name: CI

on: [ push, pull_request ]

env:
  FACIL_FORCE_REGENERATE: 1
  FACIL_FAIL_ON_CHANGED_OUTPUT: 1
  connectionString: Data Source=localhost;Database=FacilTest;User ID=sa;Password=CXTxgxnkzcTcLMCwKjqi4XbKgwFtw;TrustServerCertificate=True

jobs:
  ci:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: './global.json'
          dotnet-version: '6' # Needed by DB project

      - name: Restore tools
        run: dotnet tool restore

      - name: Check code format
        run: dotnet fantomas --check .

      - name: Build generator
        run: dotnet build src/Facil.Generator -c Release

      - name: Build package project
        run: dotnet build src/Facil.Package -c Release

      # Pack in a separate step (fails for some reason with "empty lib/" error if using <GeneratePackageOnBuild>)
      - name: Pack
        run: dotnet pack src/Facil.Package -c Release

      - name: Push
        if: startsWith(github.ref, 'refs/tags/v/')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "**/Facil*.nupkg" -s "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY" --skip-duplicate
