name: Action to build and publish the project as a nuget package to github package registry

on: [push, workflow_dispatch]
      
jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion
    
    #Build/pack the project
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: './global.json'
        dotnet-version: '6' # Needed by DB project

    - name: Restore tools
      run: dotnet tool restore

    - name: Check code format
      run: dotnet fantomas --check .

    - name: Build generator
      run: dotnet build src/Facil.Generator -c Release

    - name: Build package project
      run: dotnet build src/Facil.Package -c Release

    # Pack in a separate step (fails for some reason with "empty lib/" error if using <GeneratePackageOnBuild>)
    - name: Pack
      run: dotnet pack src/Facil.Package -c Release

    - name: Upload NuGet package to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: nugetPackage
        path: ./bin/Release/ 
        
    #Push NuGet package to GitHub packages
    - name: Download nuget package artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: nugetPackage
    - name: Prep packages
      run: dotnet nuget add source --username yourusername --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bdcodestuff/index.json"
    - name: Push package to GitHub packages 
      run: dotnet nuget push nugetPackage/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }}  --source "github"